# commande pour compiler make compilation
compilation: main.c
	sudo gcc main.c -lSDL -lpthread -o main 

# commande pour simuler make simulation
simulation: main.c
	sudo ./main

# commande a utiliser imperativement avant un push
clean:
	sudo rm -rf *.o

